Traceback (most recent call last):
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/Caskroom/mambaforge/base/envs/climate-guide/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cdo.sinfoc(input=str(path_tos), options='--verbose')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [4][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m cdo[38;5;241m.[39msinfoc([38;5;28minput[39m[38;5;241m=[39m[38;5;28mstr[39m([43mpath_tos[49m), options[38;5;241m=[39m[38;5;124m'[39m[38;5;124m--verbose[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'path_tos' is not defined
NameError: name 'path_tos' is not defined

